### ISSUE TITLE
Default install hangs

### ISSUE THREAD

**Issue by g105b** [stuartherbert/sublime-phpunit#18]
I think this is as simple as me not having the phpunit.xml file at the time of installation, but after installing the package sublime hangs on my system when opening a command palette or right clicking. Removing the package manually from my system fixed the problem.

Ubuntu 12.10, 64bit
Sublime Text 2 v2.0.1 build 2217

**Comment by stuartherbert** [comment]
Glad that @Yrwein patch has helped. This patch has been merged.

I've also pushed some additional fixes which should help. Please let me know if you have any further problems.
