### ISSUE TITLE
context menu slowdown in php files

### ISSUE THREAD

**Issue by C0dy** [stuartherbert/sublime-phpunit#20]
Hello,

this plugin slows down the context menü when i right click into an php file.
The contextmenu hangs for about 2-3 seconds and than it appears.

It onlyhappens by right clicking into the code-view-part of an php file.

Can you please take a look into this ? Thanks!

best regards....

**Comment by dfanica** [comment]
hey @stuartherbert, is there any way I can make it not show in the right click menu... I don't really use it like that and it's a pain every time I right click it hangs for 3-5 seconds. just an option would to turn it on/off would do fine! Thanks for the awesome work. I use it combination with Chain of Command to run on save (Ctrl+S) ... works wonders!

**Comment by dfanica** [comment]
By commenting out the phpunit_flush_cache from the context menu everything is running smooth.
Can I ask, what is phpunit_flush_cache doing as I never saw it in the actual drop down menu.

file: \Sublime Text 3\Packages\PHPUnit\Context.sublime-menu

<pre>
[
    { "caption": "-" },
    {
        "caption": "PHPUnit",
        "children":
        [
            // { "command": "phpunit_flush_cache" },
            { "command": "phpunit_run_tests" },
            { "command": "phpunit_open_test_class" },
            { "command": "phpunit_open_class_being_tested" },
            { "command": "phpunit_open_phpunit_xml" },
            { "command": "phpunit_run_this_phpunit_xml" },
            { "command": "phpunit_run_all_tests" },
            { "command": "phpunit_not_available" }
         ]
    }
]
</pre>

**Comment by stuartherbert** [comment]
I've just pushed some changes which should speed things up a lot for most people.

I've also added a new 'context_menu' setting in the preferences file. Set this to 'false', and it will disable all of the context menus.

Let me know if further changes are required.
