### ISSUE TITLE
Accept phpunit.xml with other file names

### ISSUE THREAD

**Issue by Surt** [stuartherbert/sublime-phpunit#34]
I would like to have the option to select a phpunit xml file with other names, as for example `phpunit-test-this.xml`. Actually, only `phpunit.xml` is accepted in the sidebar right-button command.

**Comment by stuartherbert** [comment]
I've just added a new setting to the config file - phpunit_xml_aliases. You can add your `phpunit-test-this.xml` to this list, and it should be fully supported by the plugin.

Please let me know if you have any problems using this new feature.
