### ISSUE TITLE
Open phpunit.xml uses incorrect file

### ISSUE THREAD

**Issue by JoakimLofgren** [stuartherbert/sublime-phpunit#49]
Seems like the [folder exclusion setting](https://github.com/stuartherbert/sublime-phpunit/blob/master/phpunit.py#L19) is not used, so it goes into `vendor/` and grabs the first it finds...
Even though `app/phpunit.xml.dist` is _"closer"_ than `vendor/.../phpunit.xml`

I use the default plugin settings and I don't have a `app/phpunit.xml` file.

**Comment by stuartherbert** [comment]
Thanks for the bug report. You're absolutely right - this setting isn't used.

I've just pushed a fix which should use this setting. Hopefully that will solve your problem.
