### ISSUE TITLE
Run rempte phpunit

### ISSUE THREAD

**Issue by aftabnaveed** [stuartherbert/sublime-phpunit#51]
is it possible to execute remote phpunit, I have a vagrant box which has my project files, I would like to run tests on that box from sublime text.

Thank you

**Comment by dsposito** [comment]
:+1:

**Comment by stuartherbert** [comment]
Hi,

Not really possible at the moment. The plugin currently has no way of knowing that you're using a remote box of any kind.

Best regards,
Stu
