### ISSUE TITLE
Error loading color scheme

### ISSUE THREAD

**Issue by dans98** [stuartherbert/sublime-phpunit#55]
I just tried to run some unit tests and I'm getting the following error.

"
Error loading color scheme
Packages/phpunit/color-schemes/phix-dark.hidden-tmTheme: Unable
to open Packages/phpunit/color-schemes/phix-dark.hidden-tmTheme
"

**Comment by gerardroche** [comment]
I think

```
panel_settings.set('color_scheme', 'Packages/phpunit/color-schemes/phix-dark.hidden-tmTheme')
```

should be 

```
panel_settings.set('color_scheme', 'Packages/PHPUnit/color-schemes/phix-dark.hidden-tmTheme')
```

**Comment by dans98** [comment]
Are you saying that's something i need to do, or that's an issue with the code?

just to be clear, i don't have any special settings currently set. Package control auto updated to the latest version, and then I started getting this error. Phpunit still runs as expected, i just get this popup error every time it runs.

**Comment by stuartherbert** [comment]
It's a code error, which only happens on case-sensitive filesystems.

I've just pushed a fix for this. It should appear via Package Control soon. Please let me know if it solves your problem. And thanks to @gerardroche for pointing out the fix.

**Comment by dans98** [comment]
Stuart,
The package just auto updated and is now back to normal and working perfectly, thank you!
