### ISSUE TITLE
Issue during on_save event.

### ISSUE THREAD

**Issue by danielmitd** [stuartherbert/sublime-phpunit#66]
Console shows errors after saving a phpunit test file:

```
AttributeError: 'RunPhpunitOnSave' object has no attribute 'top_folder'
```

**Comment by gerardroche** [comment]
It looks like you have different plugin installed. You have the plugin [PHPUnit](https://packagecontrol.io/search/phpunit) by stuartherbert installed.

This plugin is PHPUnitKit.
